services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://auth_user:auth_password@backend-db-1:5432/auth_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SECRET_KEY: super_secret_key
      REFRESH_SECRET: refresh_super_secret_key
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    networks:
      - auth-network
    command: ["node", "src/server.js"]  # <== Запускаем правильный файл

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    networks:
      - auth-network

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge
